### ISSUE TITLE
Key error occurs when the last name is empty

### ISSUE THREAD

**Issue by fffw2** [philgyford/foursquare-feeds#8]
When the last name of the Swarm account is empty, a key error occurs.
If the key does not exist, an empty string should be the default value.

```python
./generate_feeds.py --kind kml -vv --all
1901 checkins to fetch
Fetched 1-250
...
Fetched 1751-2000
Fetched 1901 checkins from the API
Traceback (most recent call last):
  File "/content/foursquare-feeds/./generate_feeds.py", line 355, in <module>
    generator.generate(kind=kind)
  File "/content/foursquare-feeds/./generate_feeds.py", line 68, in generate
    filepath = self._generate_kml_file(checkins)
  File "/content/foursquare-feeds/./generate_feeds.py", line 211, in _generate_kml_file
    user_name = "{} {}".format(user["firstName"], user["lastName"])
KeyError: 'lastName'
```

![image](https://github.com/user-attachments/assets/72947bc1-a617-41bd-8f08-34fed207f385)

**Comment by philgyford** [comment]
I think I've fixed that in the current version on `master`. Can you give it a try and let me know if it works for you?

**Comment by fffw2** [comment]
Thank you. The issue has been resolved.
