### ISSUE TITLE
"NameError: name 'parse' is not defined." running on macOS python3.12

### ISSUE THREAD

**Issue by TheQL** [philgyford/foursquare-feeds#9]
I have created a venv and ran `pip install -r requirements.txt`

First run failed with `ModuleNotFoundError: No module named 'six.moves'`
Got around that with `pip install --upgrade six`

Now I am stuck with this:
```
# ./generate_feeds.py -vv
Traceback (most recent call last):
  File "./generate_feeds.py", line 356, in <module>
    generator.generate(kind=kind)
  File "./generate_feeds.py", line 60, in generate
    checkins = self._get_recent_checkins()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./generate_feeds.py", line 76, in _get_recent_checkins
    results = self._get_checkins_from_api()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./generate_feeds.py", line 112, in _get_checkins_from_api
    return self.client.users.checkins(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venvs/foursquare-feeds/lib/python3.12/site-packages/foursquare/__init__.py", line 339, in checkins
    return self.GET('{USER_ID}/checkins'.format(USER_ID=USER_ID), params, multi=multi)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venvs/foursquare-feeds/lib/python3.12/site-packages/foursquare/__init__.py", line 307, in GET
    return self.requester.GET(self._expanded_path(path), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venvs/foursquare-feeds/lib/python3.12/site-packages/foursquare/__init__.py", line 239, in GET
    result = _get(url, headers=headers, params=params, timeout=self.get_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venvs/foursquare-feeds/lib/python3.12/site-packages/foursquare/__init__.py", line 790, in _get
    param_string = _foursquare_urlencode(params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venvs/foursquare-feeds/lib/python3.12/site-packages/foursquare/__init__.py", line 891, in _foursquare_urlencode
    k = parse.quote(_as_utf8(k), safe=safe_chars)
        ^^^^^
NameError: name 'parse' is not defined. Did you mean: 'vars'?
```

Which is sad because I wanted to save these before Foursquare shuts down and not sure if this will work afterwards.

**Comment by philgyford** [comment]
Obviously this hadn't been updated in a long time, and the requirements were pretty out of date.

I've just updated the `requirements.txt` and it works for me using Python 3.12. Give it another go now.

**Comment by TheQL** [comment]
Thanks! It's running now, taking a long time with "--all" ;)

**Comment by philgyford** [comment]
Glad to hear it's working!
